CREATE OR REPLACE TRIGGER PL03ZAD01
    BEFORE DELETE
    ON EMP
BEGIN
    RAISE_APPLICATION_ERROR(-20500, 'Usuwanie zablokowane');
END;

CREATE OR REPLACE TRIGGER PL03ZAD02
    BEFORE INSERT OR UPDATE
    ON EMP
    FOR EACH ROW
BEGIN
    IF :NEW.sal < 1000 THEN
        RAISE_APPLICATION_ERROR(-20500, 'Zarobki nie moga byc ponizej 1000!');
    END IF;
END;

INSERT INTO EMP
VALUES ((SELECT NVL(MAX(EMPNO) + 1, 1) FROM EMP), 'Kowalski', NULL, NULL, CURRENT_DATE, 1000, NULL, 10);

CREATE TABLE Budzet
(
    wartos INT NOT NULL
);

INSERT INTO Budzet
VALUES ((SELECT SUM(sal) FROM EMP));

CREATE OR REPLACE TRIGGER PL03ZAD03
    BEFORE INSERT OR UPDATE OR DELETE
    ON EMP
BEGIN
    UPDATE Budzet SET wartos = (SELECT SUM(sal) FROM EMP);
END;


CREATE OR REPLACE TRIGGER PL03ZAD04
    BEFORE INSERT OR UPDATE OR DELETE
    ON EMP
    FOR EACH ROW
DECLARE
    v_count INT;
BEGIN
    IF INSERTING THEN
        SELECT COUNT(*) INTO v_count FROM EMP WHERE ENAME = :NEW.ENAME;
        IF v_count > 0 THEN
            RAISE_APPLICATION_ERROR(-20500, 'Pracownik o tym nazwisku juz istnieje!');
        END IF;
    ELSIF UPDATING AND :NEW.ename != :OLD.ename THEN
        :NEW.SAL := :OLD.SAL;
    ELSIF :OLD.sal > 0 THEN
        RAISE_APPLICATION_ERROR(-20500, 'Nie wolno usuwac pracownika z niezerowa pensja!');
    END IF;
END;

INSERT INTO EMP
VALUES ((SELECT NVL(MAX(EMPNO) + 1, 1) FROM EMP), 'Kowalski', NULL, NULL, CURRENT_DATE, 1000, NULL, 10);

UPDATE EMP
SET ENAME = 'Malinowsi'
WHERE EMPNO = 7938;

DELETE
FROM EMP
WHERE EMPNO = 7938;

CREATE OR REPLACE TRIGGER PL03ZAD05
    BEFORE UPDATE OR DELETE
    ON EMP
    FOR EACH ROW
BEGIN
    IF UPDATING AND :NEW.SAL < :OLD.SAL THEN
        :NEW.SAL := :OLD.SAL;
    ELSIF DELETING THEN
        RAISE_APPLICATION_ERROR(-20500, 'Nie wolno usuwać pracowników');
    END IF;
END;